compatibility_date = "2021-10-07"
name = "worker"
# type = "javascript" is required to use the `[build]` section
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm install && npm run build"
[build.upload]
# The "modules" upload format is required for all projects that export a Durable Objects class
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "TORRENT", class_name = "Torrent"}]

[[migrations]]
tag = "v0.1" # Should be unique for each entry
new_classes = ["Torrent"]
